services:
  db:
    image: postgres:15
    container_name: auth_server_db
    restart: always
    ports:
      - '15432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SeniorCare
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: auth_server
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '5000:3000'
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: nestapp

volumes:
  pgdata:
